### Test backend server
GET http://localhost:4000/


### GET ALL MOVIES
GET http://localhost:4000/movies


### GET MOVIE BY ID
GET http://localhost:4000/movies/2



### CREATE MOVIE
POST http://localhost:4000/movies/create
Content-Type: application/json


{
    "title": "Inception",
    "description": "A thief enters the dreams of others to steal secrets.",
    "genre": "Sci-Fi",
    "language": "English",
    "duration_min": 148,
    "rating": 5,
    "poster_url": "https://static1.srcdn.com/wordpress/wp-content/uploads/2020/01/Inception-Movie-Poster.jpg",
    "trailer_url": "https://www.bing.com/videos/riverview/relatedvideo?q=inception&&mid=594F8B54EBE4BB4C9687594F8B54EBE4BB4C9687&churl=https%3a%2f%2fwww.youtube.com%2fchannel%2fUCTCjFFoX1un-j7ni4B6HJ3Q&FORM=VRDGAR",
    "release_date": "2010-07-16"
}


### UPDATE MOVIE
PUT http://localhost:4000/movies/update/4
Content-Type: application/json

{
    "title": "Inception Updated",
    "description": "A skilled thief enters people's dreams to steal valuable secrets.",
    "genre": "Sci-Fi",
    "language": "English",
    "duration_min": 148,
    "rating": 5,
    "poster_url": "https://example.com/inception-new.jpg",
    "trailer_url": "https://example.com/inception-trailer",
    "release_date": "2010-07-16"
}

### DELETE MOVIE
DELETE http://localhost:5000/movies/delete/4



### GET ALL THEATRES
GET http://localhost:4000/theatres

### GET THEATRE BY ID
GET http://localhost:4000/theatres/1


### CREATE THEATRE
POST http://localhost:4000/theatres/create
Content-Type: application/json

{
    "name": "Miraj Cinemas",
    "city": "Belagavi",
    "address": "College Road, Belagavi"
}

### UPDATE THEATRE
PUT http://localhost:4000/theatres/update/1
Content-Type: application/json

{
    "name": "PVR Cinemas Updated",
    "city": "Belagavi",
    "address": "New Address, Belagavi"
}

### DELETE THEATRE
DELETE http://localhost:4000/theatres/delete/99


### GET ALL SCREENS
GET http://localhost:4000/screens


### GET  SCREEN BY ID

GET http://localhost:4000/screens/1


### CREATE SCREEN
POST http://localhost:4000/screens/create
Content-Type: application/json

{
    "theatre_id": 1,
    "name": "Screen 1"
}

### UPDATE SCREEN
PUT http://localhost:4000/screens/update/1
Content-Type: application/json

{
    "theatre_id": 1,
    "name": "Screen 1 Updated"
}

### DELETE SCREEN
DELETE http://localhost:4000/screens/delete/1


### GET SEATS FOR SCREEN
GET http://localhost:4000/screens/2/seats

### CREATE SEAT
POST http://localhost:4000/screens/2/seats/create
Content-Type: application/json

{
    "row_label": "A",
    "seat_number": 1,
    "tier": "regular"
}


### UPDATE SEAT
PUT http://localhost:4000/seats/update/1
Content-Type: application/json

{
    "row_label": "A",
    "seat_number": 1,
    "tier": "premium"
}

### DELETE SEAT
DELETE http://localhost:4000/seats/delete/1














### 1. Check backend
GET http://localhost:4000/

### 2. Register a new user
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "MovieBooking123"
}

### 3. Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "MovieBooking123"
}

### 4. Test incorrect password
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "WrongPassword123"
}

### 5. Logout
POST http://localhost:4000/api/auth/logout
Content-Type: application/json



### Send registration OTP
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "tostorepersonal@gmail.com",
  "password": "MovieBooking123"
}


### Verify email OTP
POST http://localhost:4000/api/auth/verify-otp
Content-Type: application/json

{
  "email": "tostorepersonal@gmail.com",
  "otp": "697445"
}